repos:
    - repo: local
      hooks:
          - id: lint
            pass_filenames: false
            always_run: true
            name: lint
            entry: make lint
            language: system
            types: [python]
          - id: test
            pass_filenames: false
            always_run: true
            name: test
            entry: make test
            language: system
            types: [python]
